import Head from "next/head"
import styles from "../styles/Home.module.scss"

export default function Home() {
  return (
    <>
      <Head>
        <title>Billzonian</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.hero}>
          <h1>Billzonian</h1>
          <p>A pretty cool fork of English</p>
        </section>
      </main>
    </>
  )
}
