import Head from "next/head"
import styles from "../styles/Home.module.scss"

const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? ""

export default function Home() {
  return (
    <>
      <Head>
        <title>Billzonian</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={basePath + "/favicon.ico"} />
      </Head>
      <main>
        <p>frick</p>
      </main>
    </>
  )
}
